# Generated by Django 4.2 on 2025-08-13 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('org_id', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MastersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=20)),
                ('tablename', models.CharField(max_length=255, unique=True)),
                ('auth_groundman', models.BooleanField()),
                ('auth_curator', models.BooleanField()),
                ('auth_scorer', models.BooleanField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminuserlist', to='super_admin_user.adminuserlist')),
            ],
        ),
        migrations.AddField(
            model_name='adminuserlist',
            name='superadmin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superadmins', to='super_admin_user.superadmin'),
        ),
    ]
